config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users

  resources :documents do
    get :delete, on: :member
  end

  resources :templates do
    get :delete, on: :member
    get :select, on: :member
  end

  resources :pictures, only: [:create]

  resources :record, only: [:index]

  namespace :admin do
    resources :users do
      get :delete, on: :member
    end

    resources :documents, only: [:show]

    resources :pictures, only: [:index, :show, :destroy] do
      get :delete, on: :member
    end

    resources :web_hooks, except: [:show] do
      get :delete, on: :member
    end

    resources :sidekiq, only: %w( index )
  end

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/document.rb
# == Schema Information
#
# Table name: documents
#
#  id         :integer          not null, primary key
#  title      :string           default(""), not null
#  markdown   :text             default(""), not null
#  draft_flag :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Document < ActiveRecord::Base
  validates_presence_of :title, :markdown

  has_many :user_documents, dependent: :destroy
  has_many :users, through: :user_documents

  scope :draft, -> { where(draft_flag: true) }
  scope :publish, -> { where(draft_flag: false) }
  scope :search_title, ->(keyword) { keyword ? Document.where(['title LIKE ?', "%#{PGconn.escape(keyword)}%"]) : Document.all }
  scope :search_markdown, ->(keyword) { keyword ? Document.where(['markdown LIKE ?', "%#{PGconn.escape(keyword)}%"]) : Document.all }

  def self.id_is(id)
    find_by(id: id.to_i)
  end

  def create_markdown
    FileJob.perform_later id, nil
  end

  def update_markdown(old_title)
    FileJob.perform_later id, old_title
  end

  def destroy_markdown
    FileJob.perform_later nil, title
  end

  def is_draft?
    draft_flag
  end

  def is_publish?
    !draft_flag
  end
end

app/controllers/admin/documents_controller.rb
class Admin::DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_document

  def show
  end

  private

  def load_document
    @document = Document.id_is(params[:id]) if params[:id]
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_document

  def index
    @users = User.all

    if params[:user].present?
      @documents = User.id_is(params[:user]).documents
    else
      @documents = Document.all
    end

    if params[:title].present?
      params[:title].split(' ').each do |title|
        @documents = @documents.search_title title
      end
    end

    if params[:keyword].present?
      params[:keyword].split(' ').each do |keyword|
        @documents = @documents.search_markdown keyword
      end
    end

    @documents = @documents.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def show
  end

  def new
    @document = Document.new
    @templates = Template.order(:id).each do |template|
      template.replace_title current_user
    end
  end

  def create
    @document = Document.new document_params
    @result = @document.save

    if @result
      @document.user_documents.create user_id: current_user.id
      if @document.is_draft?
        flash[:notice] = 'ドキュメントを下書きしました。'
      else
        WebHookJob.perform_later current_user.id, @document.id, 'create'
        @document.create_markdown
        flash[:notice] = 'ドキュメントを公開しました。'
      end
    end

    render :submit
  end

  def edit
    @templates = Template.order(:id).each do |template|
      template.replace_title current_user
    end
  end

  def update
    old_title = @document.title
    was_draft = @document.is_draft?
    @result = @document.update document_params

    if @result
      unless @document.users.id_is(current_user.id)
        @document.user_documents.create user_id: current_user.id
      end

      if was_draft && @document.is_publish?
        WebHookJob.perform_later current_user.id, @document.id, 'create'
        @document.create_markdown
      elsif @document.is_publish?
        WebHookJob.perform_later current_user.id, @document.id, 'update'
        @document.update_markdown old_title
      end

      flash[:notice] = 'ドキュメントを更新しました。'
    end

    render :submit
  end

  def delete
  end

  def destroy
    @document.destroy_markdown
    @result = @document.destroy

    if @result
      flash[:notice] = 'ドキュメントを削除しました。'
    else
      flash[:alert] = 'ドキュメントを削除できませんでした。'
    end

    redirect_to documents_path
  end

  private

  def load_document
    @document = Document.id_is(params[:id]) if params[:id]
  end

  def document_params
    params.require(:document).permit :title, :markdown, :draft_flag
  end
end

app/views/documents/_delete.html.slim
.uk-modal-dialog
  a.uk-modal-close.uk-close

  .uk-modal-header
    h4.bold
      = fa_icon 'trash', text: 'ドキュメント削除'

  | 「#{document.title}」を削除しますか?

  .uk-modal-footer.uk-text-right
    .uk-button-group
      = link_to document_path, method: :delete, class: 'uk-button uk-button-danger' do
        = fa_icon 'trash', text: '削除'
      button.uk-button.uk-modal-close
        = fa_icon 'times', text: 'キャンセル'

app/views/documents/_dropdown.html.slim
.uk-button-dropdown data-uk-dropdown="{ mode: 'click' }"
  button.uk-button.uk-button-large.uk-button-primary
    = fa_icon 'search'

  .uk-dropdown
    = form_tag documents_path, method: :get, class: 'uk-form uk-form-stacked' do
      .uk-form-row
        = select_tag :user, options_from_collection_for_select(users, :id, :name), { prompt: 'ユーザー', class: 'uk-width-1-1' }
      .uk-form-row
        .uk-form-icon
          i.uk-icon-font
          = text_field_tag :title, params[:title], placeholder: 'タイトル'
      .uk-form-row
        .uk-form-icon
          i.uk-icon-paragraph
          = text_field_tag :keyword, params[:keyword], placeholder: 'キーワード'

      .uk-nav-side
        .uk-nav-divider

      .uk-form-row
        button.uk-button.uk-button-primary onClick="$('.uk-dropdown > .uk-form').submit()"
          = fa_icon 'search', text: '検索'

app/views/documents/_form.html.slim
= form_for document, html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|
  = f.check_box :draft_flag, { class: 'uk-hidden' }
  .uk-form-row
    .uk-grid
      .uk-width-medium-1-3
        = select_tag :template, options_from_collection_for_select(templates, :id, :title), { prompt: 'テンプレート', class: 'uk-form-large uk-width-1-1' }
      .uk-margin-top.uk-visible-small
      .uk-width-medium-2-3
        = f.text_field :title, autofocus: true, class: 'uk-form-large uk-width-1-1', placeholder: 'タイトル'
  .uk-form-row#upload-paste
    = f.text_area :markdown, 'data-uk-htmleditor' => '{ markdown: true }'
  .uk-form-row
    .uk-grid
      .uk-width-medium-2-3
        .uk-placeholder.uk-text-center#upload-drop
          i.uk-icon-cloud-upload.uk-icon-medium.uk-text-muted.uk-margin-small-right
          | 画像をドラッグもしくは
          a.uk-form-file
            | 選択
            input#upload-select type="file" multiple="multiple"
          | してアップロード
      .uk-margin-top.uk-visible-small
      .uk-width-medium-1-3.uk-text-center
        .uk-button-group
          button.uk-button.uk-button-big.uk-button-primary#document-publish
            = fa_icon 'globe', text: '公開'
          button.uk-button.uk-button-big#document-draft
            = fa_icon 'pencil', text: '下書き'

- if document.id && document.is_publish?
  coffee:
    $('#document-draft').attr('disabled', true)

javascript:
  websocket_url = '#{request.raw_host_with_port}/websocket'
  user_account = '#{current_user.account}'

coffee:
  marked.setOptions {
    breaks: true
    gfm: true
    highlight: (code, lang) ->
      hljs.highlightAuto(code, [lang]).value
  }
  dispatcher = new WebSocketRails(websocket_url)
  channel = dispatcher.subscribe(user_account)
  channel.bind 'create_picture', ( data ) ->
    content = '\n[![' + data.file_name + '](' + data.image + ' \"' + data.file_name + '\")](' + data.url + ')\n'
    $('.CodeMirror')[0].CodeMirror.replaceSelection(content)
  ukUploadSettings = {
    action: '/pictures'
    allow: '*.(jpeg|jpg|png|gif|pdf)'
    notallowed: ->
      UIkit.notify({ message: '不正な画像ファイルです。', timeout: 3000, status: 'danger' })
    error: ->
      UIkit.notify({ message: 'アップロード中にエラーが発生しました。', timeout: 3000, status: 'danger' })
    abort: ->
      UIkit.notify({ message: 'アップロードを中断しました。', timeout: 3000, status: 'danger' })
    params: {
      authenticity_token: $('meta[name=\"csrf-token\"]').attr('content')
    }
  }
  uk_select = UIkit.uploadSelect($('#upload-select'), ukUploadSettings)
  uk_drop = UIkit.uploadDrop($('#upload-drop'), ukUploadSettings)
  $('#template').on 'change', ->
    if $(this).val() == ''
      $(this).addClass('placeholder')
    else
      $(this).removeClass('placeholder')
    if $(':selected').attr('value') != ''
      $.ajax {
        'url': '/templates/' + $(':selected').attr('value') + '/select'
        'type': 'GET'
        'data-type': 'html'
      }
  $('#template').change()
  $('#document-publish').on 'click', (event) ->
    event.preventDefault()
    $('#document_draft_flag').prop('checked', false)
    $('.uk-form').submit()
  $('#document-draft').on 'click', (event) ->
    event.preventDefault()
    $('#document_draft_flag').prop('checked', true)
    $('.uk-form').submit()
  $(document).ready ->
    $('.uk-htmleditor-preview').addClass('markdown-body')
  $('#upload-paste').on 'paste', (event) ->
    event.preventDefault()
    # event からクリップボードのアイテムを取り出す
    items = event.originalEvent.clipboardData.items
    if items[0].type.indexOf('image') == 0
      result = upload_files_with_ajax(items[0].getAsFile())
    return
  upload_files_with_ajax = (file) ->
    event.preventDefault()
    formData = new FormData
    formData.append('files[]', file, 'from_clipboard.png')
    formData.append('authenticity_token', $('meta[name=\"csrf-token\"]').attr('content'))
    $.ajax '/pictures', {
      type: 'POST'
      contentType: false
      processData: false
      data: formData
      error: ->
      # アップロードエラー処理
      success: (res) ->
        console.log res
      # アップロード成功処理
    }

app/views/documents/_list.html.slim
- if documents.empty?
  .uk-alert.uk-alert-warning
    = fa_icon 'times', text: 'ドキュメントは存在しません。'

- else
  dl.uk-description-list-line
    - documents.includes(:users).each do |document|
      dt
        = link_to document.title, document_path(document.id), class: 'uk-h3 uk-margin-right'
        - if document.is_draft?
          span.uk-text-muted.uk-margin-small-right data-uk-tooltip="" title="下書き"
            = fa_icon 'file'
        = link_to edit_document_path(document.id) do
          span.uk-text-success data-uk-tooltip="" title="編集"
            = fa_icon 'pencil'
        = link_to delete_document_path(document.id), remote: true do
          span.uk-text-danger.uk-margin-small-left data-uk-tooltip="" title="削除"
            = fa_icon 'trash'

      dd
        = fa_icon 'users'
        span.uk-margin-small-left #{document.users.pluck(:name).join(', ')}
        span.uk-margin-left
        = fa_icon 'calendar'
        span.uk-margin-small-left #{I18n.l document.updated_at, format: :short}

      - if params[:keyword].present?
        - keywords = params[:keyword].split ' '
        dd
          = highlight excerpt(document.markdown, keywords.first, radius: 30, omission: ''), keywords

app/views/documents/_sidebar.html.slim
.uk-panel.uk-panel-box
  = form_tag documents_path, method: :get, class: 'uk-form uk-form-stacked' do
    .uk-panel-title.bold
      = fa_icon 'search', text: '検索'

    .uk-nav-side
      .uk-nav-divider

    .uk-form-row
      = select_tag :user, options_from_collection_for_select(users, :id, :name), { prompt: 'ユーザー', class: 'uk-width-1-1' }
    .uk-form-row
      .uk-form-icon
        i.uk-icon-font
        = text_field_tag :title, params[:title], placeholder: 'タイトル'
    .uk-form-row
      .uk-form-icon
        i.uk-icon-paragraph
        = text_field_tag :keyword, params[:keyword], placeholder: 'キーワード'

    .uk-nav-side
      .uk-nav-divider

    .uk-form-row
      button.uk-button.uk-button-primary onClick="$('.uk-panel > .uk-form').submit()"
        = fa_icon 'search', text: '検索'

app/views/documents/edit.html.slim
- @title = 'ドキュメント編集'

h2.bold
  = fa_stacked_icon 'file-text inverse', base: 'square', text: @title

= render partial: 'documents/form', locals: { document: @document, templates: @templates }

coffee:
  $('#nav-documents').addClass('uk-active')

app/views/documents/index.html.slim
- @title = 'ドキュメント'

.relative
  h2.bold
    = fa_stacked_icon 'file-text inverse', base: 'square', text: @title
  .absolute-top.absolute-right.uk-visible-small
    = render partial: 'documents/dropdown', locals: { users: @users }

.uk-grid
  .uk-width-medium-3-10
    .uk-hidden-small
      = render partial: 'documents/sidebar', locals: { users: @users }
  .uk-width-medium-7-10
    = render partial: 'documents/list', locals: { documents: @documents }
    = paginate @documents

javascript:
  user = '#{params[:user]}'

coffee:
  $('#nav-documents').addClass('uk-active')
  $('select#user').val(user)
  $('select#user').on 'change', ->
    if $(this).val() == ''
      $(this).addClass('placeholder')
    else
      $(this).removeClass('placeholder')
  $('select#user').change()

app/views/documents/new.html.slim
- @title = 'ドキュメント作成'

h2.bold
  = fa_stacked_icon 'file-text inverse', base: 'square', text: @title

= render partial: 'documents/form', locals: { document: @document, templates: @templates }

coffee:
  $('#nav-documents').addClass('uk-active')

app/views/documents/show.html.slim
- @title = @document.title

article.uk-article
  dd.uk-text-muted
    span.uk-article-title.uk-margin-right #{@document.title}
    - if @document.is_draft?
      span.uk-text-muted.uk-margin-small-right data-uk-tooltip="" title="下書き"
        = fa_icon 'file'
    = link_to edit_document_path do
      span.uk-text-success data-uk-tooltip="" title="編集"
        = fa_icon 'pencil'
    = link_to delete_document_path, remote: true do
      span.uk-text-danger.uk-margin-small-left data-uk-tooltip="" title="削除"
        = fa_icon 'trash'

    p
      = fa_icon 'users'
      span.uk-margin-small-left #{@document.users.pluck(:name).join(', ')}
      span.uk-margin-left
      = fa_icon 'calendar'
      span.uk-margin-small-left #{I18n.l @document.updated_at, format: :short}

  hr.uk-article-divider

  .markdown-body

javascript:
  markdown = '#{raw escape_javascript(@document.markdown)}';

coffee:
  $('#nav-documents').addClass('uk-active')
  marked.setOptions {
    breaks: true
    gfm: true
    highlight: (code) ->
      return hljs.highlightAuto(code).value
  }
  $('.markdown-body').html marked(markdown)