config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users

  resources :documents do
    get :delete, on: :member
  end

  resources :templates do
    get :delete, on: :member
    get :select, on: :member
  end

  resources :pictures, only: [:create]

  resources :record, only: [:index]

  namespace :admin do
    resources :users do
      get :delete, on: :member
    end

    resources :documents, only: [:show]

    resources :pictures, only: [:index, :show, :destroy] do
      get :delete, on: :member
    end

    resources :web_hooks, except: [:show] do
      get :delete, on: :member
    end

    resources :sidekiq, only: %w( index )
  end

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/web_hook.rb
# == Schema Information
#
# Table name: web_hooks
#
#  id         :integer          not null, primary key
#  url        :string           default(""), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  name       :string           default(""), not null
#

class WebHook < ActiveRecord::Base
  validates_presence_of :name, :url

  def self.id_is(id)
    find_by(id: id.to_i)
  end
end

app/controllers/admin/web_hooks_controller.rb
class Admin::WebHooksController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_web_hook

  def index
    @web_hooks = WebHook.order(updated_at: :desc).page(params[:page]).per(20)
  end

  def show
  end

  def new
    @web_hook = WebHook.new
  end

  def create
    @web_hook = WebHook.new web_hook_params
    @result = @web_hook.save
    flash[:notice] = 'WebHookを作成しました。' if @result
    render :submit
  end

  def edit
  end

  def update
    @result = @web_hook.update web_hook_params
    flash[:notice] = 'WebHookを更新しました。' if @result
    render :submit
  end

  def delete
  end

  def destroy
    @result = @web_hook.destroy

    if @result
      flash[:notice] = 'WebHookを削除しました。'
    else
      flash[:alert] = 'WebHookを削除できませんでした。'
    end

    redirect_to admin_web_hooks_path
  end

  private

  def load_web_hook
    @web_hook = WebHook.id_is(params[:id]) if params[:id]
  end

  def web_hook_params
    params.require(:web_hook).permit :name, :url
  end
end

app/views/admin/web_hooks/_delete.html.slim
.uk-modal-dialog
  a.uk-modal-close.uk-close

  .uk-modal-header
    h4.bold
      = fa_icon 'trash', text: 'WebHook削除'

  | 「#{web_hook.name}」を削除しますか?

  .uk-modal-footer.uk-text-right
    .uk-button-group
      = link_to admin_web_hook_path, method: :delete, class: 'uk-button uk-button-danger' do
        = fa_icon 'trash', text: '削除'
      button.uk-button.uk-modal-close
        = fa_icon 'times', text: 'キャンセル'

app/views/admin/web_hooks/_form.html.slim
.uk-modal-dialog style="padding-bottom: 0"
  a.uk-modal-close.uk-close

  = form_for [:admin, web_hook], html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|
    .uk-modal-header
      h4.bold
        = fa_icon 'anchor', text: title

    .uk-form-row
      .uk-form-icon
        i.uk-icon-font
        = f.text_field :name, autofocus: true, placeholder: '名前', style: 'padding-left: 30px;'
      .uk-form-help-block#web_hook-name-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-link
        = f.text_field :url, placeholder: 'URL', style: 'padding-left: 30px;'
      .uk-form-help-block#web_hook-url-error

    .uk-modal-footer.uk-text-right
      .uk-button-group
        button.uk-button.uk-button-primary
          = fa_icon 'floppy-o', text: '保存'
        button.uk-button.uk-modal-close
          = fa_icon 'times', text: 'キャンセル'

app/views/admin/web_hooks/_list.html.slim
.uk-overflow-container
  table.uk-table.uk-table-striped
    thead
      tr
        th style="width: 150px;"
          = link_to new_admin_web_hook_path, class: 'uk-button uk-button-mini uk-button-primary', remote: true do
            = fa_icon 'plus', text: '作成'
        th.bold style="width: 150px;" 名前
        th.bold URL
    tbody
      - web_hooks.each do |web_hook|
        tr
          td
            = link_to edit_admin_web_hook_path(web_hook.id), class: 'uk-button uk-button-mini uk-button-success uk-margin-small-right', remote: true do
              = fa_icon 'pencil', text: '編集'
            = link_to delete_admin_web_hook_path(web_hook.id), class: 'uk-button uk-button-mini uk-button-danger', remote: true do
              = fa_icon 'trash', text: '削除'
          td #{web_hook.name}
          td #{web_hook.url}

app/views/admin/web_hooks/index.html.slim
- @title = 'WebHook'

h2.bold
  = fa_stacked_icon 'slack inverse', base: 'square', text: @title

= render partial: 'admin/web_hooks/list', locals: { web_hooks: @web_hooks }
= paginate @web_hooks

coffee:
  $('#nav-admin').addClass('uk-active')