config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users

  resources :documents do
    get :delete, on: :member
  end

  resources :templates do
    get :delete, on: :member
    get :select, on: :member
  end

  resources :pictures, only: [:create]

  resources :record, only: [:index]

  namespace :admin do
    resources :users do
      get :delete, on: :member
    end

    resources :documents, only: [:show]

    resources :pictures, only: [:index, :show, :destroy] do
      get :delete, on: :member
    end

    resources :web_hooks, except: [:show] do
      get :delete, on: :member
    end

    resources :sidekiq, only: %w( index )
  end

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  account                :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  name                   :string           default(""), not null
#  created_at             :datetime
#  updated_at             :datetime
#  admin_flag             :boolean          default(FALSE), not null
#  grade                  :integer          default(1), not null
#  email                  :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :validatable, :recoverable
  validates_presence_of :name
  before_save :update_account!

  has_many :user_documents, dependent: :destroy
  has_many :documents, through: :user_documents

  include Grade

  def self.id_is(id)
    find_by(id: id.to_i)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    params.delete(:password) if params[:password].blank?
    params.delete(:password_confirmation) if params[:password_confirmation].blank?

    clean_up_passwords
    update_attributes(params, *options)
  end

  def is_admin?
    admin_flag
  end

  private

  def update_account!
    self.account = email.match(/\A(.+)@/)[1]
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_user

  def index
    @users = User.order(updated_at: :desc).page(params[:page]).per(20)
  end

  def show
    @documents = @user.documents.order(updated_at: :desc).page(params[:page]).per(20)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    @result = @user.save
    flash[:notice] = 'ユーザーを作成しました。' if @result
    render :submit
  end

  def edit
  end

  def update
    @result = @user.update_without_current_password user_params
    flash[:notice] = 'ユーザーを更新しました。' if @result
    render :submit
  end

  def delete
  end

  def destroy
    @result = @user.destroy

    if @result
      flash[:notice] = 'ユーザーを削除しました。'
    else
      flash[:alert] = 'ユーザーを削除できませんでした。'
    end

    redirect_to admin_users_path
  end

  private

  def load_user
    @user = User.id_is(params[:id]) if params[:id]
  end

  def user_params
    params.require(:user).permit :email, :name, :grade, :password, :password_confirmation, :admin_flag
  end
end

app/views/admin/users/_delete.html.slim
.uk-modal-dialog
  a.uk-modal-close.uk-close

  .uk-modal-header
    h4.bold
      = fa_icon 'trash', text: 'ユーザー削除'

  | 「#{user.account} (#{user.name})」を削除しますか?

  .uk-modal-footer.uk-text-right
    .uk-button-group
      = link_to admin_user_path, method: :delete, class: 'uk-button uk-button-danger' do
        = fa_icon 'trash', text: '削除'
      button.uk-button.uk-modal-close
        = fa_icon 'times', text: 'キャンセル'

app/views/admin/users/_form.html.slim
.uk-modal-dialog style="padding-bottom: 0"
  a.uk-modal-close.uk-close

  = form_for [:admin, user], html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|
    .uk-modal-header
      h4.bold
        = fa_icon 'user', text: title

    .uk-form-row
      .uk-form-icon
        i.uk-icon-envelope
        = f.text_field :email, autofocus: true, placeholder: 'メールアドレス', style: 'padding-left: 30px;'
      .uk-form-help-block#user-email-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-font
        = f.text_field :name, placeholder: '名前', style: 'padding-left: 30px;'
      .uk-form-help-block#user-name-error
    .uk-form-row
      = f.select :grade, Grade::SELECT, {}, { class: 'uk-width-1-1' }
      .uk-form-help-block#user-grade-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-key
        = f.password_field :password, autocomplete: 'off', placeholder: 'パスワード', style: 'padding-left: 30px;'
      .uk-form-help-block#user-password-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-key
        = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'パスワード (確認)', style: 'padding-left: 30px;'
      .uk-form-help-block#user-password-confirmation-error
    .uk-form-row
      = f.check_box :admin_flag, class: 'uk-margin-left'
      = f.label :admin_flag, '管理者', class: 'uk-margin-left'

    .uk-modal-footer.uk-text-right
      .uk-button-group
        button.uk-button.uk-button-primary
          = fa_icon 'floppy-o', text: '保存'
        button.uk-button.uk-modal-close
          = fa_icon 'times', text: 'キャンセル'

app/views/admin/users/_list.html.slim
.uk-overflow-container
  table.uk-table.uk-table-striped
    thead
      tr
        th style="width: 150px;"
          = link_to new_admin_user_path, class: 'uk-button uk-button-mini uk-button-primary', remote: true do
            = fa_icon 'plus', text: '作成'
        th.bold style="width: 300px;" メールアドレス
        th.bold style="width: 150px;" 名前
        th.bold style="width: 50px;" 学年
        th.bold style="width: 50px;" 管理者
        th.bold ドキュメント
    tbody
      - users.includes(:documents).each do |user|
        tr
          td
            = link_to edit_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-success uk-margin-small-right', remote: true do
              = fa_icon 'pencil', text: '編集'
            = link_to delete_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-danger', remote: true do
              = fa_icon 'trash', text: '削除'
          td #{user.email}
          td #{user.name}
          td #{user.grade_text}
          td.uk-text-center
            - if user.is_admin?
              = fa_icon 'check'
          td
            = link_to admin_user_path(user.id) do
              = fa_icon 'files-o', text: "#{user.documents.size} ドキュメント"

app/views/admin/users/index.html.slim
- @title = 'ユーザー'

h2.bold
  = fa_stacked_icon 'users inverse', base: 'square', text: @title

= render partial: 'admin/users/list', locals: { users: @users }
= paginate @users

coffee:
  $('#nav-admin').addClass('uk-active')

app/views/admin/users/show.html.slim
- @title = @user.account

p
  span.uk-h2.bold
    = fa_stacked_icon 'user inverse', base: 'square', text: @title
  span.uk-h4.uk-text-muted.uk-margin-small-left
    | (#{@user.name})

= render partial: 'admin/documents/list', locals: { documents: @documents }
= paginate @documents

coffee:
  $('#nav-admin').addClass('uk-active')