config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  devise_for :users

  resources :documents do
    get :delete, on: :member
  end

  resources :templates do
    get :delete, on: :member
    get :select, on: :member
  end

  resources :pictures, only: [:create]

  resources :record, only: [:index]

  namespace :admin do
    resources :users do
      get :delete, on: :member
    end

    resources :documents, only: [:show]

    resources :pictures, only: [:index, :show, :destroy] do
      get :delete, on: :member
    end

    resources :web_hooks, except: [:show] do
      get :delete, on: :member
    end

    resources :sidekiq, only: %w( index )
  end

  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{@title} | 書庫
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag

  body
    .uk-modal

    nav.uk-navbar.uk-navbar-attached
      .uk-container.uk-container-center
        = link_to root_path, class: 'uk-navbar-brand' do
          span.brand.bold 書庫

        - if user_signed_in?
          ul.uk-navbar-nav.uk-hidden-small
            li.uk-parent#nav-documents data-uk-dropdown=""
              = link_to documents_path do
                = fa_icon 'file-text', text: 'ドキュメント'
              .uk-dropdown.uk-dropdown-navbar
                ul.uk-nav.uk-nav-navbar
                  li
                    = link_to documents_path do
                      = fa_icon 'bars fw', text: 'ドキュメント一覧'
                  li
                    = link_to new_document_path do
                      = fa_icon 'plus fw', text: 'ドキュメント作成'

            li.uk-parent#nav-templates data-uk-dropdown=""
              = link_to templates_path do
                = fa_icon 'file', text: 'テンプレート'
              .uk-dropdown.uk-dropdown-navbar
                ul.uk-nav.uk-nav-navbar
                  li
                    = link_to templates_path do
                      = fa_icon 'bars fw', text: 'テンプレート一覧'
                  li
                    = link_to new_template_path do
                      = fa_icon 'plus fw', text: 'テンプレート作成'

            li#nav-record
              = link_to record_index_path do
                = fa_icon 'leanpub', text: '議事録'

        .uk-navbar-flip.uk-hidden-small
          ul.uk-navbar-nav
            - if user_signed_in?
              - if current_user.is_admin?
                li.uk-parent#nav-admin data-uk-dropdown=""
                  a
                    = fa_icon 'cog', text: '管理'
                  .uk-dropdown.uk-dropdown-navbar
                    ul.uk-nav.uk-nav-navbar
                      li
                        = link_to admin_users_path  do
                          = fa_icon 'users fw', text: 'ユーザー'
                      li
                        = link_to admin_pictures_path  do
                          = fa_icon 'photo fw', text: '画像'
                      li
                        = link_to admin_web_hooks_path  do
                          = fa_icon 'slack fw', text: 'WebHook'
                      li
                        = link_to admin_sidekiq_index_path  do
                          = fa_icon 'child fw', text: 'Sidekiq'
              li.uk-parent#nav-user data-uk-dropdown=""
                a
                  = fa_icon 'user', text: current_user.account
                .uk-dropdown.uk-dropdown-navbar
                  ul.uk-nav.uk-nav-navbar
                    li
                      = link_to edit_user_registration_path(current_user.id)  do
                        = fa_icon 'pencil fw', text: '編集'
                    li
                      = link_to destroy_user_session_path, method: :delete
                        = fa_icon 'sign-out fw', text: 'ログアウト'

            - else
              li
                = link_to new_user_session_path
                  = fa_icon 'sign-in', text: 'ログイン'

        .uk-navbar-flip.uk-visible-small
          a.uk-navbar-toggle href="#navbar-offcanvas" data-uk-offcanvas=""

    .uk-offcanvas#navbar-offcanvas
      .uk-offcanvas-bar.uk-offcanvas-bar-flip
        ul.uk-nav.uk-nav-offcanvas.uk-nav-parent-icon data-uk-nav=""
          - if user_signed_in?
            li.uk-nav-header
              = fa_icon 'file-text fw', text: 'ドキュメント'
            li
              = link_to documents_path do
                = fa_icon 'bars fw', text: 'ドキュメント一覧'
            li
              = link_to new_document_path do
                = fa_icon 'plus fw', text: 'ドキュメント作成'

            li.uk-nav-header
              = fa_icon 'file fw', text: 'テンプレート'
            li
              = link_to templates_path do
                = fa_icon 'bars fw', text: 'テンプレート一覧'
            li
              = link_to new_template_path do
                = fa_icon 'plus fw', text: 'テンプレート作成'

            li.uk-nav-header
              = fa_icon 'leanpub fw', text: '議事録'
            li
              = link_to record_index_path do
                = fa_icon 'leanpub fw', text: '議事録'

            - if current_user.is_admin?
              li.uk-nav-header
                = fa_icon 'cog fw', text: '管理'
              li
                = link_to admin_users_path  do
                  = fa_icon 'users fw', text: 'ユーザー'
              li
                = link_to admin_pictures_path  do
                  = fa_icon 'photo fw', text: '画像'
              li
                = link_to admin_web_hooks_path  do
                  = fa_icon 'slack fw', text: 'WebHook'
              li
                = link_to admin_sidekiq_index_path  do
                  = fa_icon 'child fw', text: 'Sidekiq'

            li.uk-nav-header
              = fa_icon 'user fw', text: current_user.account
            li
              = link_to edit_user_registration_path(current_user.id)  do
                = fa_icon 'cog fw', text: '設定'
            li
              = link_to destroy_user_session_path, method: :delete
                = fa_icon 'sign-out fw', text: 'ログアウト'

          - else
            li
              = link_to new_user_session_path
                = fa_icon 'sign-in fw', text: 'ログイン'

    .uk-container.uk-container-center.uk-margin-top.uk-margin-bottom
      = yield

    .uk-container.uk-container-center.uk-margin-bottom
      footer
        .relative
          small
            | &copy; #{Shoko::Application.config.copyright}
            - unless Rails.env.production?
              span.absolute-right.revision rev.#{Shoko::Application.config.git_revision}

- if notice
  javascript:
    UIkit.notify({ message: '#{notice}', timeout: 3000 });

- if alert
  javascript:
    UIkit.notify({ message: '#{alert}', timeout: 3000, status: 'danger' });